<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Channel extends Model {

	protected $guarded = [];


	public function threads() {
		return $this->hasMany( 'App\Thread' );
	}

	public function getRouteKeyName() {
//		return parent::getRouteKeyName(); // TODO: Change the autogenerated stub
		return 'slug';
	}


	public function path() {
		return "/channels/{$this->id}";
	}
}
